(()=>{'use strict';
const P='/materyaller/5-sinif/hafta01/sunum/';
const $=s=>document.querySelector(s),stage=$('#stage'),player=$('#player');let period=1,idx=0,route=[],touchX=null,lessonData=null;
const titles={1:'Ön Bilgini Yokla',2:'Günlük Yaşamdan Başla',3:'Bilgi Nedir?',4:'Teknoloji Nedir?',5:'Bilişim Teknolojileri',6:'Bilgiyle Ne Yapıyoruz?',7:'Kavramları Birbirine Bağla',7.5:'İletişim · Bilişim · BİT Köprüsü',8:'Kullanım Amacını Düşün',9:'Örnekleri İncele',10:'Kullanım Alanlarını Fark Et',11:'Sınıflandırma Ölçütü',12:'Aynı Teknoloji · Farklı Amaç',13:'Sınıflandırmaya Hazırlan',14:'Kullanım Alanına Yerleştir',15:'Aynı Nesneler · Farklı Ölçüt',16:'1. Ders Çıkışı',17:'30 Saniyede Hatırla',18:'İhtiyaç Kalır · Araç Değişir',19:'Mektuptan Mesaja',20:'Haritadan Navigasyona',21:'Filmli Kameradan Telefon Kamerasına',22:'Masaüstünden Taşınabilir Bilgisayara',23:'Geçmişten Günümüze Karşılaştırma Lensi',24:'Geçmişten Günümüze Eşleştir',28:'Oluşturulmuş Film Sahnesi',29:'Ne Merak Ettin?',30:'Aynı Sahne · Kamera Arkası',31:'Aynı Teknik · Farklı Sahneler',32:'Bu Sahneyi Hangi Teknolojiler Oluşturdu?',33:'Aynı İşi Yapanları Bir Araya Getir',34:'Teknoloji Nerede, Ne Sağlıyor?',38:'Hızlı Kontrol'};
const copy={
7.5:['BİLGİYLE ÇALIŞMAK · BİLGİYİ AKTARMAK','Bilgi; toplanır, işlenir, saklanır ve iletilir. Bilişim bu süreçlerle bilgi üzerinde çalışmayı; iletişim ise bilginin insanlar arasında aktarılmasını sağlar. BİT, bu iki alanı teknolojiyle buluşturur.'],
11:['SINIFLANDIRMA ÖLÇÜTÜ','Bir teknolojiyi sınıflandırırken önce “Nerede?” değil, “Ne amaçla kullanılıyor?” sorusunu sor.'],
12:['AYNI TEKNOLOJİ · FARKLI AMAÇ','Aynı araç farklı bağlamlarda farklı kullanım alanlarına girebilir. Önemli olan kullanım amacıdır.'],
13:['SINIFLANDIRMAYA HAZIRLAN','Şimdi teknolojileri kullanım amaçlarına göre gruplandırmaya hazırsın.'],
15:['AYNI NESNELER · FARKLI ÖLÇÜT','Aynı nesneler farklı ölçütlere göre farklı biçimlerde gruplanabilir. Sınıflandırmada kullandığın ölçüt sonucu değiştirir.'],
16:['1. DERS ÇIKIŞI','Bugün öğrendiğin üç kavramı söyle: bilgi, teknoloji ve bilişim teknolojileri. Ardından bir teknolojiyi kullanım alanına göre sınıflandır.'],
17:['30 SANİYEDE HATIRLA','Bir önceki dersten aklında kalan üç kavramı ve bir sınıflandırma örneğini söyle.'],
18:['İHTİYAÇ KALIR · ARAÇ DEĞİŞİR','İnsanların iletişim kurma, yol bulma, görüntü kaydetme ve bilgiyle çalışma ihtiyaçları sürer; bu ihtiyaçları karşılayan araçlar zamanla değişir.'],
19:['MEKTUPTAN MESAJA','Geçmişte mektup, günümüzde mesaj ve e-posta. Araç değişti; iletişim kurma ihtiyacı kaldı.'],
20:['HARİTADAN NAVİGASYONA','Geçmişte basılı harita, günümüzde navigasyon. Araç değişti; yol bulma ihtiyacı kaldı.'],
21:['FİLMLİ KAMERADAN TELEFON KAMERASINA','Araç değişti; görüntü kaydetme ihtiyacı kaldı.'],
22:['MASAÜSTÜNDEN TAŞINABİLİR BİLGİSAYARA','Araçlar küçüldü ve taşınabilir hâle geldi; bilgiyle çalışma ihtiyacı sürdü.'],
23:['GEÇMİŞTEN GÜNÜMÜZE KARŞILAŞTIRMA LENSİ','Karşılaştırırken üç şeye bak: Ne aynı kaldı? Ne değişti? Değişim hangi ihtiyacı daha kolay karşılıyor?'],
28:['FİLM SAHNESİ','Bir film sahnesinin gerçekte nasıl oluşturulmuş olabileceğini düşün. Görüntüde gerçek görünen ayrıntıları fark et ve çekim sürecine ilişkin tahmin kur.'],
29:['NE MERAK ETTİN?','1. Bu sahne nasıl oluşturulmuş olabilir?\n2. Gerçek görünen hangi ayrıntıyı fark ettin?\n3. Bu sahnenin çekimi hakkında neyi merak ediyorsun?'],
30:['AYNI SAHNE · KAMERA ARKASI','01 Ham çekim → 02 Arka plan görüntüsü → 03 Birleştirilmiş sahne. Çekimde kullanılan yeşil arka plan, sonradan başka bir görüntüyle değiştirilir. Son görüntüde ne değişti, ne aynı kaldı?'],
31:['AYNI TEKNİK · FARKLI SAHNELER','Film sahnesi · Hava durumu · Sanal stüdyo. Yeşil ekran, farklı görüntülerin aynı sahnede birleştirilmesini sağlar. Bu örneklerde yeşil ekran ne işe yarıyor?'],
32:['BU SAHNEYİ HANGİ TEKNOLOJİLER OLUŞTURDU?','Az önce gördüğün film ve yayın örneklerini düşün. Görüntüyü çekmek, sesi almak, ışığı oluşturmak veya görüntüyü değiştirmek için neler kullanılmış olabilir?'],
33:['AYNI İŞİ YAPANLARI BİR ARAYA GETİR','Söylediğiniz teknolojileri ne işe yaradıklarına göre gruplayın: görüntüyü oluşturur · sesi oluşturur · ortamı/ışığı düzenler · görüntüyü işler/değiştirir. Bir teknoloji birden fazla işe yarayabilir mi?'],
34:['TEKNOLOJİ NEREDE, NE SAĞLIYOR?','Başka nerede kullanılır? Ne sağlıyor? Nerede daha faydalı? Ortak sonucunuz ne? Teknolojileri yalnız adlarıyla değil, ne işe yaradıklarına ve nerede kullanıldıklarına göre de düşünebiliriz.']};
const r1=[1,2,3,4,5,6,7,7.5,8,9,10,11,12,13,14,15,16],r2=[17,18,19,23,24,28,29,30,31,32,33,34,38];
const ready=fetch('/lesson-player-data.json',{cache:'no-store'}).then(r=>r.json()).then(x=>lessonData=x).catch(()=>{});
function textSurface(n){const d=document.createElement('div');d.className='activity';const [h,p]=copy[n]||[titles[n]||'Ders Adımı','Öğretmen yönlendirmeli sınıf tartışması.'];d.innerHTML=`<div class="kicker">${period}. DERS · DERS AKIŞI</div><h2>${h}</h2><p class="desc" style="white-space:pre-line;font-size:16px;line-height:1.8">${p}</p>`;return d}
function imageNode(n){if(n<=10&&Number.isInteger(n)){const im=document.createElement('img');im.src=P+String(n).padStart(2,'0')+'.png';im.alt=titles[n]||'Ders görseli';return im}return textSurface(n)}
function activityData(id){return lessonData?.courses?.['5-sinif']?.weeks?.['01']?.lessonPlayer?.activities?.find(a=>a.id===id)}
function activityNode(id){const a=activityData(id),box=document.createElement('div');box.className='activity';if(!a){box.innerHTML='<h2>Ders Etkinliği</h2><p class="desc">Etkinlik verisi yüklenemedi.</p>';return box}box.innerHTML=`<div class="kicker">${a.phase||'ETKİNLİK'}</div><h2>${a.title}</h2><p class="desc">${a.description||''}</p>`;if(a.kind==='classify')classify(box,a);if(a.kind==='match')match(box,a);if(a.kind==='quiz')quiz(box,a);return box}
function classify(box,a){let sel='';const chips=document.createElement('div');chips.className='chips';a.items.forEach(x=>{const b=document.createElement('button');b.className='chip';b.textContent=x;b.onclick=()=>{sel=x;[...chips.children].forEach(c=>c.classList.remove('sel'));b.classList.add('sel')};chips.appendChild(b)});const z=document.createElement('div');z.className='zones';a.categories.forEach(c=>{const d=document.createElement('button');d.className='zone';d.innerHTML=`<b>${c}</b><span></span>`;d.onclick=()=>{if(!sel)return;const p=document.createElement('span');p.className='placed';p.textContent=sel;d.querySelector('span').appendChild(p);sel='';[...chips.children].forEach(x=>x.classList.remove('sel'))};z.appendChild(d)});box.append(chips,z)}
function match(box,a){let L=null;const w=document.createElement('div');w.className='match';const l=document.createElement('div'),r=document.createElement('div');l.className=r.className='matchcol';a.pairs.forEach((p,i)=>{const b=document.createElement('button');b.className='matchitem';b.textContent=p.left;b.onclick=()=>{L=i;[...l.children].forEach(x=>x.classList.remove('sel'));b.classList.add('sel')};l.appendChild(b)});[...a.pairs].sort(()=>Math.random()-.5).forEach(p=>{const b=document.createElement('button');b.className='matchitem';b.textContent=p.right;b.onclick=()=>{if(L===null)return;if(a.pairs[L].right===p.right){l.children[L].classList.add('done');b.classList.add('done');L=null;[...l.children].forEach(x=>x.classList.remove('sel'))}};r.appendChild(b)});w.append(l,r);box.appendChild(w)}
function quiz(box,a){a.questions.forEach(q=>{const d=document.createElement('div');d.className='q';d.innerHTML=`<strong>${q.prompt}</strong><div class="opts"></div>`;q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='opt';b.textContent=o;b.onclick=()=>{[...d.querySelectorAll('.opt')].forEach(x=>x.classList.remove('good','bad'));b.classList.add(i===q.correct?'good':'bad');d.querySelectorAll('.opt')[q.correct]?.classList.add('good');let f=d.querySelector('.feedback');if(!f){f=document.createElement('p');f.className='feedback';d.appendChild(f)}f.textContent=q.feedback};d.querySelector('.opts').appendChild(b)});box.appendChild(d)})}
function extensionNode(){const d=document.createElement('div');d.className='activity';d.innerHTML='<div class="kicker">EK ÇALIŞMA · SÜRE VARSA</div><h2>Teknoloji Araştırmacıları</h2><p class="desc">Bu çalışma çekirdek 40 dakikalık akışın dışındadır.</p><div class="ext"><ol><li>Bir bilişim teknolojisi seçin.</li><li>Geçmişte ve günümüzde nasıl kullanıldığını karşılaştırın.</li><li>Kullanım alanını ve ne sağladığını belirleyin.</li><li>60 saniyelik kısa bir sınıf paylaşımı yapın.</li></ol></div>';return d}
function render(){stage.querySelectorAll(':scope > *:not(.nav)').forEach(x=>x.remove());const n=route[idx];let node;if(n===14)node=activityNode('classify-use');else if(n===24)node=activityNode('match-past-present');else if(n===38)node=activityNode('quiz-evidence');else if(n===25)node=extensionNode();else node=imageNode(n);stage.insertBefore(node,$('#next'));$('#meta').textContent=`${period}. DERS · ${titles[n]||''}`;$('#counter').textContent=`${idx+1} / ${route.length}`;$('#prev').disabled=idx===0;$('#next').disabled=idx===route.length-1;$('#alts').classList.toggle('show',period===2&&n===19);$('#ext').classList.toggle('show',period===2&&n===24)}
async function start(p){period=p;idx=0;route=p===1?[...r1]:[...r2];player.classList.add('open');player.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';stage.querySelector('.loading')?.remove();await ready;render()}
function close(){player.classList.remove('open');player.setAttribute('aria-hidden','true');document.body.style.overflow='';if(document.fullscreenElement)document.exitFullscreen?.()}
function step(d){const ni=idx+d;if(ni<0||ni>=route.length)return;idx=ni;render()}
$('[data-start="1"]').onclick=()=>start(1);$('[data-start="2"]').onclick=()=>start(2);$('#close').onclick=close;$('#prev').onclick=()=>step(-1);$('#next').onclick=()=>step(1);$('#full').onclick=()=>player.requestFullscreen?.();$('#alts').onclick=()=>{route.splice(idx+1,0,20,21,22);$('#alts').classList.remove('show');step(1)};$('#ext').onclick=()=>{route.splice(idx+1,0,25);$('#ext').classList.remove('show');step(1)};addEventListener('keydown',e=>{if(!player.classList.contains('open'))return;if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1);if(e.key==='Escape')close()});stage.addEventListener('touchstart',e=>touchX=e.changedTouches[0]?.clientX,{passive:true});stage.addEventListener('touchend',e=>{if(touchX==null)return;const dx=e.changedTouches[0].clientX-touchX;touchX=null;if(Math.abs(dx)>50)step(dx>0?-1:1)},{passive:true});
})();