(()=>{'use strict';
const A='/hafta01-assets/',P='/materyaller/5-sinif/hafta01/sunum/';
const $=s=>document.querySelector(s), stage=$('#stage'), player=$('#player');let period=1,idx=0,route=[],touchX=null,lessonData=null,AS={};
const spriteParts=Array.from({length:26},(_,i)=>A+'b64/sprite-'+String(i).padStart(2,'0')+'.txt');
const videoParts=Array.from({length:11},(_,i)=>A+'b64/video-'+String(i).padStart(2,'0')+'.txt');
async function b64(parts,mime){const t=await Promise.all(parts.map(async u=>{const r=await fetch(u);if(!r.ok)throw Error(u);return r.text()}));return'data:'+mime+';base64,'+t.join('')}
const ready=Promise.all([b64(spriteParts,'image/webp').then(x=>AS.sprite=x),b64(videoParts,'video/mp4').then(x=>AS.video=x),fetch('/lesson-player-data.json').then(r=>r.json()).then(x=>lessonData=x)]);
const extra={7.5:0,11:1,12:2,13:3,15:4,16:5,17:6,18:7,19:8,20:9,21:10,22:11,23:12,29:13,30:14,31:15,32:16,33:17,34:18};
const titles={1:'Ön Bilgini Yokla',2:'Günlük Yaşamdan Başla',3:'Bilgi Nedir?',4:'Teknoloji Nedir?',5:'Bilişim Teknolojileri',6:'Bilgiyle Ne Yapıyoruz?',7:'Kavramları Birbirine Bağla',7.5:'İletişim · Bilişim · BİT Köprüsü',8:'Kullanım Amacını Düşün',9:'Örnekleri İncele',10:'Kullanım Alanlarını Fark Et',11:'Sınıflandırma Ölçütü',12:'Aynı Teknoloji · Farklı Amaç',13:'Sınıflandırmaya Hazırlan',14:'Kullanım Alanına Yerleştir',15:'Aynı Nesne · Farklı Ölçüt',16:'1. Ders Çıkışı',17:'30 Saniyede Hatırla',18:'İhtiyaç Kalır · Araç Değişir',19:'Mektuptan Mesaja',20:'Haritadan Navigasyona',21:'Filmli Kameradan Telefon Kamerasına',22:'Masaüstünden Taşınabilir Bilgisayara',23:'Geçmişten Günümüze Karşılaştırma Lensi',24:'Geçmişten Günümüze Eşleştir',28:'Oluşturulmuş Film Sahnesi',29:'Ne Merak Ettin?',30:'Aynı Sahne · Kamera Arkası',31:'Aynı Teknik · Farklı Sahneler',32:'Bu Sahneyi Hangi Teknolojiler Oluşturdu?',33:'Aynı İşi Yapanları Bir Araya Getir',34:'Teknoloji Nerede, Ne Sağlıyor?',38:'Hızlı Kontrol'};
const r1=[1,2,3,4,5,6,7,7.5,8,9,10,11,12,13,14,15,16],r2=[17,18,19,23,24,28,29,30,31,32,33,34,38];
function spriteStyle(n){return`width:min(100%,960px);aspect-ratio:16/9;background-image:url(${AS.sprite});background-size:100% 1900%;background-position:center ${extra[n]*100/18}%;background-repeat:no-repeat`}
function imageNode(n){const div=document.createElement('div');if(n<=10&&Number.isInteger(n)){const im=document.createElement('img');im.src=P+String(n).padStart(2,'0')+'.png';im.alt=titles[n]||'Ders görseli';div.appendChild(im)}else{div.setAttribute('style',spriteStyle(n));div.setAttribute('role','img');div.setAttribute('aria-label',titles[n]||'Ders görseli')}return div}
function activityData(id){return lessonData?.courses?.['5-sinif']?.weeks?.['01']?.lessonPlayer?.activities?.find(a=>a.id===id)}
function activityNode(id){const a=activityData(id),box=document.createElement('div');box.className='activity';if(!a){box.innerHTML='<h2>Ders Etkinliği</h2><p class="desc">Etkinlik verisi yüklenemedi.</p>';return box}box.innerHTML=`<div class="kicker">${a.phase||'ETKİNLİK'}</div><h2>${a.title}</h2><p class="desc">${a.description||''}</p>`;if(a.kind==='classify')renderClassify(box,a);if(a.kind==='match')renderMatch(box,a);if(a.kind==='quiz')renderQuiz(box,a);return box}
function renderClassify(box,a){let selected='';const chips=document.createElement('div');chips.className='chips';a.items.forEach(x=>{const b=document.createElement('button');b.className='chip';b.textContent=x;b.onclick=()=>{selected=x;[...chips.children].forEach(c=>c.classList.remove('sel'));b.classList.add('sel')};chips.appendChild(b)});const z=document.createElement('div');z.className='zones';a.categories.forEach(c=>{const d=document.createElement('button');d.className='zone';d.innerHTML=`<b>${c}</b><span></span>`;d.onclick=()=>{if(!selected)return;const p=document.createElement('span');p.className='placed';p.textContent=selected;d.querySelector('span').appendChild(p);selected='';[...chips.children].forEach(x=>x.classList.remove('sel'))};z.appendChild(d)});box.append(chips,z);if(a.teacherPrompt){const p=document.createElement('p');p.className='desc';p.textContent='Öğretmen yönlendirmesi: '+a.teacherPrompt;box.appendChild(p)}}
function renderMatch(box,a){let L=null;const wrap=document.createElement('div');wrap.className='match';const left=document.createElement('div'),right=document.createElement('div');left.className=right.className='matchcol';a.pairs.forEach((p,i)=>{const b=document.createElement('button');b.className='matchitem';b.textContent=p.left;b.onclick=()=>{L=i;[...left.children].forEach(x=>x.classList.remove('sel'));b.classList.add('sel')};left.appendChild(b)});[...a.pairs].sort(()=>Math.random()-.5).forEach(p=>{const b=document.createElement('button');b.className='matchitem';b.textContent=p.right;b.onclick=()=>{if(L===null)return;const correct=a.pairs[L].right===p.right;const lb=left.children[L];if(correct){lb.classList.add('done');b.classList.add('done');L=null;[...left.children].forEach(x=>x.classList.remove('sel'))}else{b.classList.add('sel');setTimeout(()=>b.classList.remove('sel'),500)}};right.appendChild(b)});wrap.append(left,right);box.appendChild(wrap)}
function renderQuiz(box,a){a.questions.forEach(q=>{const d=document.createElement('div');d.className='q';d.innerHTML=`<strong>${q.prompt}</strong><div class="opts"></div>`;q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='opt';b.textContent=o;b.onclick=()=>{[...d.querySelectorAll('.opt')].forEach(x=>x.classList.remove('good','bad'));b.classList.add(i===q.correct?'good':'bad');d.querySelectorAll('.opt')[q.correct]?.classList.add('good');let f=d.querySelector('.feedback');if(!f){f=document.createElement('p');f.className='feedback';d.appendChild(f)}f.textContent=q.feedback};d.querySelector('.opts').appendChild(b)});box.appendChild(d)})}
function extensionNode(){const d=document.createElement('div');d.className='activity';d.innerHTML='<div class="kicker">EK ÇALIŞMA · SÜRE VARSA</div><h2>Teknoloji Araştırmacıları</h2><p class="desc">Bu çalışma çekirdek 40 dakikalık akışın dışındadır. Sınıf hızlı ilerliyorsa 24. adımdan sonra açılabilir.</p><div class="ext"><ol><li>Bir bilişim teknolojisi seçin.</li><li>Geçmişte ve günümüzde nasıl kullanıldığını karşılaştırın.</li><li>Kullanım alanını ve ne sağladığını belirleyin.</li><li>60 saniyelik kısa bir sınıf paylaşımı yapın.</li></ol></div>';return d}
function render(){stage.querySelectorAll(':scope > *:not(.nav)').forEach(x=>x.remove());const n=route[idx];let node;if(n===14)node=activityNode('classify-use');else if(n===24)node=activityNode('match-past-present');else if(n===38)node=activityNode('quiz-evidence');else if(n===25)node=extensionNode();else if(n===28){node=document.createElement('video');node.src=AS.video;node.controls=true;node.playsInline=true}else node=imageNode(n);stage.insertBefore(node,$('#next'));$('#meta').textContent=`${period}. DERS · ${titles[n]||''}`;$('#counter').textContent=`${idx+1} / ${route.length}`;$('#prev').disabled=idx===0;$('#next').disabled=idx===route.length-1;$('#alts').classList.toggle('show',period===2&&n===19);$('#ext').classList.toggle('show',period===2&&n===24)}
async function start(p){period=p;idx=0;route=p===1?[...r1]:[...r2];player.classList.add('open');player.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';stage.querySelector('.loading')?.remove();try{await ready;render()}catch(e){stage.querySelectorAll(':scope > *:not(.nav)').forEach(x=>x.remove());const d=document.createElement('div');d.className='activity';d.innerHTML='<h2>Ders hazırlanamadı.</h2><p class="desc">Sayfayı yenileyip yeniden deneyin.</p>';stage.insertBefore(d,$('#next'))}}
function close(){player.classList.remove('open');player.setAttribute('aria-hidden','true');document.body.style.overflow='';if(document.fullscreenElement)document.exitFullscreen?.()}
function step(d){const ni=idx+d;if(ni<0||ni>=route.length)return;idx=ni;render()}
$('[data-start="1"]').onclick=()=>start(1);$('[data-start="2"]').onclick=()=>start(2);$('#close').onclick=close;$('#prev').onclick=()=>step(-1);$('#next').onclick=()=>step(1);$('#full').onclick=()=>player.requestFullscreen?.();$('#alts').onclick=()=>{route.splice(idx+1,0,20,21,22);$('#alts').classList.remove('show');step(1)};$('#ext').onclick=()=>{route.splice(idx+1,0,25);$('#ext').classList.remove('show');step(1)};addEventListener('keydown',e=>{if(!player.classList.contains('open'))return;if(e.key==='ArrowRight')step(1);if(e.key==='ArrowLeft')step(-1);if(e.key==='Escape')close()});stage.addEventListener('touchstart',e=>touchX=e.changedTouches[0]?.clientX,{passive:true});stage.addEventListener('touchend',e=>{if(touchX==null)return;const dx=e.changedTouches[0].clientX-touchX;touchX=null;if(Math.abs(dx)>50)step(dx>0?-1:1)},{passive:true});
})();
