(()=>{
'use strict';
const C=window.KESKINLAB_COURSE||{}, $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], RAW='https://raw.githubusercontent.com/rkanaliz/keskinlab/main/';
let WEEKS=[], OUTCOMES={};
function dt(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d,12)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(w){return String(w.tarih_araligi||w.tarih||'').toLocaleUpperCase('tr-TR')}
async function text(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`${url} → ${r.status}`);return r.text()}
function parseBTY(t){const p=t.indexOf('const WEEKS'),a=t.indexOf('[',p),z=t.indexOf('];',a);if(p<0||a<0||z<a)throw Error('BTY veri dizisi okunamadı');return JSON.parse(t.slice(a,z+1))}
function parsePush(t){const p=t.indexOf('COURSE_WEEKS.push(...'),a=t.indexOf('[',p),z=t.lastIndexOf(']);');if(p<0||a<0||z<a)throw Error('Seçmeli veri dizisi okunamadı');return JSON.parse(t.slice(a,z+1))}
function norm(w){if(w.tarih_araligi)return w;return {...w,tarih_araligi:w.tarih||'',tema:w.unite||'',ogrenme_ciktisi:(w.kazanimlar||[]).join(' • '),surec_bilesenleri:w.kazanimlar||[],ders_saati:'2',ozel_hafta:false}}
async function load(){try{if(C.source==='bty')WEEKS=(await text(RAW+C.legacy).then(parseBTY)).map(norm);else WEEKS=(await Promise.all(C.files.map(f=>text(f).then(parsePush)))).flat().map(norm).sort((a,b)=>a.hafta_no-b.hafta_no);$('#loadNote').textContent=''}catch(e){console.warn(e);$('#loadNote').textContent='Hafta verisi yüklenemedi. Sayfayı yenileyin.';$('#loadNote').classList.add('error')}}
function parts(s){return String(s||'').split('•').map(x=>x.trim()).filter(Boolean)}
function buildOutcomes(){OUTCOMES={};for(const w of WEEKS){for(const p of parts(w.ogrenme_ciktisi)){const m=p.match(/^([A-ZÇĞİÖŞÜ]+(?:\.\d+){3,4})\.?\s*(.*)$/);if(!m)continue;const code=m[1],depth=(code.match(/\./g)||[]).length;if(depth!==C.leaf)continue;const bits=code.split('.'),group=Number(bits[C.gidx]);if(!group)continue;const o=OUTCOMES[code]||(OUTCOMES[code]={group,desc:m[2].trim(),weeks:[],steps:[]});if(!o.weeks.includes(w.hafta_no))o.weeks.push(w.hafta_no);if(!o.steps.length)o.steps=(w.surec_bilesenleri||[]).filter(Boolean)}}}
function currentIndex(){if(!WEEKS.length)return 0;const now=new Date();now.setHours(12,0,0,0);let i=WEEKS.findIndex(w=>now>=dt(w.baslangic)&&now<=dt(w.bitis));if(i>=0)return i;i=WEEKS.findIndex(w=>dt(w.baslangic)>now);return i>=0?i:WEEKS.length-1}
function title(w){return w?.ozel_hafta?(w.ders_saati||'Özel Hafta'):(w?.konu||'Ders içeriği')}
function showView(name){$$('.viewtab').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));window.scrollTo({top:$('#pageHeader')?.offsetHeight||0,behavior:'smooth'})}
function renderCurrent(){const w=WEEKS[currentIndex()];if(!w)return;const now=new Date();now.setHours(12,0,0,0);const before=now<dt(WEEKS[0].baslangic),after=now>dt(WEEKS.at(-1).bitis);$('#cwNum').textContent=String(w.hafta_no).padStart(2,'0');$('#cwDate').textContent=fmt(w);$('#cwTopic').textContent=title(w);$('#cwTheme').textContent=w.tema||'Özel hafta';$('#cwOutcome').textContent=w.ogrenme_ciktisi||'Bu hafta için öğrenme çıktısı bulunmuyor.';if(before){$('#currentHeading').textContent='Sıradaki ders hazır.';$('#cwState').textContent='DÖNEM ÖNCESİ · HAZIRLIK';$('#cwLead').textContent='Ders yılı başladığında bu alan otomatik olarak aktif haftaya döner. Şimdilik ilk ders haftasını önizliyorsun.'}else if(after){$('#currentHeading').textContent='Dönem tamamlandı.';$('#cwState').textContent='2026–2027 · TAMAMLANDI';$('#cwLead').textContent='Yıllık akış arşiv olarak erişilebilir durumda.'}else{$('#currentHeading').textContent='Sınıfta şimdi ne var?';$('#cwState').textContent='AKTİF DERS HAFTASI';$('#cwLead').textContent='Bu haftanın dersine, materyallerine ve öğretmen araçlarına tek yüzeyden ulaş.'}$('#startLesson').onclick=()=>location.hash='#hafta-'+w.hafta_no}
function renderWeeks(){let h='';WEEKS.forEach((w,i)=>{if(i===0)h+='<div class="term-sep">I. DÖNEM · 1–18. HAFTA</div>';if(i===18)h+=`<div class="term-sep">II. DÖNEM · 19–${WEEKS.length}. HAFTA</div>`;h+=`<div class="week-row ${w.ozel_hafta?'special':''}" data-week="${w.hafta_no}"><div class="wn">${String(w.hafta_no).padStart(2,'0')}</div><div class="wd">${esc(fmt(w))}</div><div><div class="wt">${esc(title(w))}</div><div class="wtheme">${esc(w.tema||'Sınav / planlama / sosyal etkinlik haftası')}</div></div><div class="ws">AÇ →</div></div>`});$('#weekList').innerHTML=h;$$('.week-row').forEach(r=>r.onclick=()=>location.hash='#hafta-'+r.dataset.week)}
function renderCurriculum(){let h='';for(let g=1;g<=C.groups;g++){const list=Object.entries(OUTCOMES).filter(([,o])=>o.group===g);h+=`<section class="theme-block"><div class="theme-top"><div class="theme-no">${esc(C.prefix+'.'+g)}</div><h3>${esc(C.themes[g]||('Bölüm '+g))}</h3><div class="theme-count">${list.length} ÇIKTI · +</div></div><div class="outcomes">${list.map(([code,o])=>`<article class="outcome"><div class="ocode">${esc(code)}</div><div class="odesc">${esc(o.desc)}</div><div class="oweeks">HAFTA ${o.weeks.join(', ')}</div><div class="osteps"><ul>${o.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div></article>`).join('')}</div></section>`}$('#curriculumRoot').innerHTML=h;$$('.theme-top').forEach(t=>t.onclick=()=>t.parentElement.classList.toggle('open'));$$('.outcome').forEach(o=>o.onclick=e=>{if(!e.target.closest('li'))o.classList.toggle('open')})}
function openLesson(no){const w=WEEKS.find(x=>Number(x.hafta_no)===Number(no));if(!w)return;$('#shell').classList.add('shell-hidden');$('#pageHeader').classList.add('shell-hidden');$('#lessonView').classList.add('active');$('#lessonNo').textContent=String(no).padStart(2,'0');$('#lessonEy').textContent=`${fmt(w)} · ${w.ders_saati||'2'} DERS SAATİ`;$('#lessonTitle').textContent=title(w);$('#lessonMeta').textContent=w.tema?`${C.unit} · ${w.tema}`:'Bu hafta ders içeriği işlenmiyor.';$('#slideTopic').textContent=title(w);$('#slideWeek').textContent=String(no).padStart(2,'0');const first=parts(w.ogrenme_ciktisi).find(x=>(x.match(/\./g)||[]).length===C.leaf)||'';const fm=first.match(/^([^\s]+)\.?\s*(.*)$/);$('#teacherOutcomeCode').textContent=fm?fm[1].replace(/\.$/,''):'ÖĞRENME ÇIKTISI';$('#teacherOutcomeText').textContent=w.ogrenme_ciktisi||'Bu hafta için öğrenme çıktısı bulunmuyor.';$('#teacherSteps').innerHTML=(w.surec_bilesenleri||[]).map(s=>`<li>${esc(s)}</li>`).join('');$('#activityText').textContent=w.etkinlik||'Haftanın öğrenci etkinliği ve sınıf içi uygulama alanı.';$('#planLink').href=C.plan.replace('{n}',w.hafta_no);window.scrollTo(0,0)}
function closeLesson(){$('#lessonView').classList.remove('active');$('#shell').classList.remove('shell-hidden');$('#pageHeader').classList.remove('shell-hidden')}
function route(){const m=location.hash.match(/^#hafta-(\d+)$/);if(m)openLesson(+m[1]);else closeLesson()}
function wire(){$('#lessonBack').onclick=()=>{history.replaceState(null,'',location.pathname);closeLesson()};$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$$('[data-top-view]').forEach(a=>a.onclick=e=>{e.preventDefault();showView(a.dataset.topView)});$$('[data-drawer-view]').forEach(a=>a.onclick=e=>{e.preventDefault();$('#drawerToggle').checked=false;showView(a.dataset.drawerView)});addEventListener('hashchange',route)}
async function init(){await load();buildOutcomes();renderCurrent();renderWeeks();renderCurriculum();wire();route()}
init();
})();
