(()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/rkanaliz/keskinlab/main/';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const COURSES={
 bty5:{name:'5. Sınıf BTY',path:'5-sinif-bty.html',source:'bty',legacy:'5-sinif-bty.html',plan:'gunluk-planlar-5sinif/hafta{n}-5sinif-bty.docx',fallback:[{hafta_no:1,tarih_araligi:'14 Eylül - 18 Eylül',tema:'Bilişim Teknolojilerinin Hayatımızdaki Yeri',konu:'Bilişim Teknolojilerinin Sınıflandırılması',ogrenme_ciktisi:'BTY.5.1.1. Günlük yaşamda kullanılan bilişim teknolojilerini sınıflandırabilme',baslangic:'2026-09-14',bitis:'2026-09-18'}]},
 bty6:{name:'6. Sınıf BTY',path:'6-sinif-bty.html',source:'bty',legacy:'6-sinif-bty.html',plan:'gunluk-planlar-6sinif/hafta{n}-6sinif-bty.docx',fallback:[{hafta_no:1,tarih_araligi:'14 Eylül - 18 Eylül',tema:'Bilişim Teknolojilerinin Hayatımızdaki Yeri',konu:'Yenilikçi Bilişim Teknolojileri',ogrenme_ciktisi:'BTY.6.1.1. Yenilikçi bilişim teknolojilerini sorgulayabilme',baslangic:'2026-09-14',bitis:'2026-09-18'}]},
 robotik:{name:'Robotik Kodlama-I',path:'robotik-kodlama.html',source:'elective',files:['robotik-data-1.js','robotik-data-2.js'],plan:'gunluk-planlar-robotik/hafta{n}-robotik-kodlama.docx',fallback:[{hafta_no:1,tarih:'14-18 Eylül 2026',unite:'RK.1.1. Robotik Kavramına Giriş',konu:'Robotik Kavramının Tanımı · Robot Nedir? · Robotik Bilimi',kazanimlar:['RK.1.1.1.1. Robotik kavramını açıklar.'],baslangic:'2026-09-14',bitis:'2026-09-18'}]},
 yapayzeka:{name:'Yapay Zekâ Uygulamaları-I',path:'yapay-zeka.html',source:'elective',files:['yapay-zeka-data-1.js','yapay-zeka-data-2.js'],plan:'gunluk-planlar-yapay-zeka/hafta{n}-yapay-zeka-uygulamalari.docx',fallback:[{hafta_no:1,tarih:'14-18 Eylül 2026',unite:'YZU.1.1. Yapay Zekâya Giriş',konu:'Yapay Zekâ Kavramı',kazanimlar:['YZU.1.1.1.1. Yapay zekânın tanımını yapar.'],baslangic:'2026-09-14',bitis:'2026-09-18'}]}
};
let EVENTS=[{date:'2026-09-14',label:'Ders Yılı Başlangıcı',type:'donem'},{date:'2026-11-16',end:'2026-11-20',label:'Ara Tatil',type:'tatil'},{date:'2027-01-25',end:'2027-02-05',label:'Yarıyıl Tatili',type:'tatil'},{date:'2027-03-08',end:'2027-03-12',label:'Ramazan Bayramı / Ara Tatil',type:'tatil'},{date:'2027-05-15',end:'2027-05-18',label:'Kurban Bayramı',type:'tatil'},{date:'2027-06-25',label:'Ders Yılı Bitişi',type:'donem'}];
let data={},displayIndex=null,manual=false;
function d(s){const [y,m,day]=String(s).split('-').map(Number);return new Date(y,m-1,day,12)}
function iso(dt){return `${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function txt(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(url+' → '+r.status);return r.text()}
function parseBTY(t){const p=t.indexOf('const WEEKS');if(p<0)throw Error('BTY verisi okunamadı');const a=t.indexOf('[',p),z=t.indexOf('];',a);if(a<0||z<a)throw Error('BTY hafta dizisi okunamadı');return JSON.parse(t.slice(a,z+1))}
function parsePush(t){const p=t.indexOf('COURSE_WEEKS.push(...'),a=t.indexOf('[',p),z=t.lastIndexOf(']);');if(p<0||a<0||z<a)throw Error('Seçmeli ders verisi okunamadı');return JSON.parse(t.slice(a,z+1))}
function norm(w){if(w.tarih_araligi)return w;return {hafta_no:Number(w.hafta_no),tarih_araligi:w.tarih||'',tema:w.unite||'',konu:w.konu||'',ogrenme_ciktisi:(w.kazanimlar||[]).join(' • '),baslangic:w.baslangic,bitis:w.bitis,etkinlik:w.etkinlik||''}}
async function loadCourse(key){const c=COURSES[key];try{if(c.source==='bty')return parseBTY(await txt(RAW+c.legacy)).map(norm);const p=await Promise.all(c.files.map(f=>txt(f).then(parsePush)));return p.flat().map(norm).sort((a,b)=>a.hafta_no-b.hafta_no)}catch(e){console.warn(key,e);return c.fallback.map(norm)}}
async function loadCalendar(){try{const t=await txt('home-calendar.js');const m=t.match(/const EVENTS = (\[[\s\S]*?\]);\s*\n\s*const TR_MONTHS/);if(m)EVENTS=JSON.parse(m[1])}catch(e){console.warn('Takvim fallback kullanılıyor',e)}}
function overlap(a1,a2,b1,b2){return d(a1)<=d(b2)&&d(a2)>=d(b1)}
function calendarFor(w){return EVENTS.filter(e=>overlap(e.date,e.end||e.date,w.baslangic,w.bitis))}
function holidayAt(today){const s=iso(today);return EVENTS.find(e=>e.type==='tatil'&&s>=e.date&&s<=(e.end||e.date))}
function currentCanonicalIndex(){const W=data.bty5||[];if(!W.length)return 0;const now=new Date();now.setHours(12,0,0,0);let i=W.findIndex(w=>now>=d(w.baslangic)&&now<=d(w.bitis));if(i>=0)return i;i=W.findIndex(w=>d(w.baslangic)>now);return i>=0?i:W.length-1}
function courseWeek(key,canonical){const arr=data[key]||[],a=canonical.baslangic,b=canonical.bitis;return arr.find(w=>overlap(w.baslangic,w.bitis,a,b))||arr.find(w=>d(w.baslangic)>=d(a))||arr.at(-1)||COURSES[key].fallback[0]}
function fmtRange(w){return String(w.tarih_araligi||'').toLocaleUpperCase('tr-TR')}
function renderCalendar(w){const items=calendarFor(w),box=$('#weekCalendarItems');box.innerHTML=items.length?items.map(e=>`<span class="cal-chip">${esc(e.label)}</span>`).join(''):'<span class="cal-chip">Normal ders haftası</span>'}
function renderCourses(w){const keys=['bty5','bty6','robotik','yapayzeka'];$('#weekStream').innerHTML=keys.map((key,i)=>{const c=COURSES[key],cw=courseWeek(key,w),topic=cw.ozel_hafta?(cw.ders_saati||'Özel hafta'):(cw.konu||'Ders akışı'),theme=cw.tema||'Haftalık akış';return `<article class="week-course"><div class="wc-num">0${i+1}</div><div><div class="wc-name">${esc(c.name)}</div><div class="wc-topic">${esc(topic)}</div><div class="wc-meta">${esc(theme)}</div></div><div class="week-actions"><a class="start" href="${c.path}#hafta-${cw.hafta_no}">Derse Başla →</a><a href="${c.plan.replace('{n}',cw.hafta_no)}">Plan ↓</a></div></article>`}).join('')}
function renderWeek(){const W=data.bty5||[];if(!W.length)return;if(displayIndex==null)displayIndex=currentCanonicalIndex();displayIndex=Math.max(0,Math.min(displayIndex,W.length-1));const w=W[displayIndex],now=new Date();now.setHours(12,0,0,0);const hol=holidayAt(now),before=now<d(W[0].baslangic),after=now>d(W.at(-1).bitis),active=now>=d(w.baslangic)&&now<=d(w.bitis)&&!manual;$('#weekNumber').textContent=String(w.hafta_no).padStart(2,'0');$('#weekDates').textContent=fmtRange(w);let status='SEÇİLİ HAFTA',heading='Haftanın ders akışı.',desc='Dört ders aynı zaman çizgisinde ilerliyor.';if(!manual&&before){status='HAZIRLIK MODU';heading='Yeni dönem hazırlanıyor.';desc='İlk ders haftası 14 Eylül 2026 tarihinde açılıyor.'}else if(!manual&&after){status='DÖNEM TAMAMLANDI';heading='2026–2027 tamamlandı.';desc='Dersler ve haftalar arşiv olarak erişilebilir.'}else if(!manual&&hol){status=hol.label.toLocaleUpperCase('tr-TR');heading='Devre bekleme modunda.';desc=`Dersler ${fmtRange(w)} haftasında yeniden başlıyor.`}else if(active){status='AKTİF DERS HAFTASI';heading='Sınıfta şimdi ne var?';desc='Bu haftanın dersleri, planları ve materyal akışı açık.'}else if(!manual){status='HAFTA SONU / GEÇİŞ';heading='Sıradaki ders haftası hazır.';desc=`Yeni ders akışı ${fmtRange(w)}.`}$('#weekStatus').textContent=status;$('#weekHeading').textContent=heading;$('#weekDescription').textContent=desc;$('#globalLiveStatus').textContent=before?'2026–2027 / hazırlık':after?'2026–2027 / tamamlandı':`2026–2027 / hafta ${String(w.hafta_no).padStart(2,'0')}`;$('#mobileLive').textContent=before?'HAZIRLIK':after?'TAMAMLANDI':`HAFTA ${String(w.hafta_no).padStart(2,'0')}`;renderCalendar(w);renderCourses(w);$('#prevWeek').disabled=displayIndex===0;$('#nextWeek').disabled=displayIndex===W.length-1}
function wireWeek(){$('#prevWeek').onclick=()=>{manual=true;displayIndex--;renderWeek()};$('#nextWeek').onclick=()=>{manual=true;displayIndex++;renderWeek()};$('#todayWeek').onclick=()=>{manual=false;displayIndex=currentCanonicalIndex();renderWeek()}}
function effects(){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(x=>io.observe(x));const bio=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('active')}),{threshold:.3});const b=$('#bridge');if(b)bio.observe(b)}else $$('.reveal').forEach(x=>x.classList.add('visible'));setTimeout(()=>$$('.reveal:not(.visible)').forEach(x=>x.classList.add('visible')),1800);const onScroll=()=>{const max=document.documentElement.scrollHeight-innerHeight,p=max?scrollY/max:0;document.documentElement.style.setProperty('--scroll',`${Math.max(0,Math.min(1,p))*100}%`);const tb=$('#timelineBody');if(tb){const r=tb.getBoundingClientRect(),vh=innerHeight;const q=Math.max(0,Math.min(1,(vh*.68-r.top)/(r.height-vh*.25)));tb.style.setProperty('--timeline',`${q*100}%`)}};addEventListener('scroll',onScroll,{passive:true});onScroll()}
function mobile(){$$('.drawer-link').forEach(a=>a.addEventListener('click',()=>{$('#mobileNavToggle').checked=false}))}
async function init(){const [b5,b6,rk,yz]=await Promise.all([loadCourse('bty5'),loadCourse('bty6'),loadCourse('robotik'),loadCourse('yapayzeka')]);data={bty5:b5,bty6:b6,robotik:rk,yapayzeka:yz};await loadCalendar();renderWeek();wireWeek();effects();mobile()}
init();
})();
