import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const strictAssets=process.argv.includes('--strict-assets');
const errors=[],warnings=[];
const MATERIAL_ROOT=path.join(ROOT,'materyaller');
const COURSE_DIRS=new Set(['5-sinif','6-sinif','robotik','yapay-zeka']);
const TOP_LEVEL=new Set(['sunum','ders-notu','ogrenci-etkinligi','infografik','hafta-ozeti','olcme-degerlendirme','ogretmen']);
const ASSESSMENT=new Set(['kisa-cevap','rubrik','kontrol-listesi']);
const TEACHER=new Set(['gozlem-formu']);
const SOURCE_EXT=new Set(['.png','.jpg','.jpeg','.pdf','.docx']);
const RASTER_EXT=new Set(['.png','.jpg','.jpeg']);
const WARN_RASTER_BYTES=Math.round(1.2*1024*1024);
const LEGACY_HTML_LINK_EXCLUDES=new Set(['5-sinif-bty.html','6-sinif-bty.html','robotik-kodlama.html','yapay-zeka.html']);
const CLASSROOM_PLAN_RULES=[['classroom-5-sinif.html',37],['classroom-6-sinif.html',37],['classroom-robotik.html',36],['classroom-yapay-zeka.html',36]];
const PLAN_RULES=[['gunluk-planlar-5sinif',37],['gunluk-planlar-6sinif',37],['gunluk-planlar-robotik',36],['gunluk-planlar-yapay-zeka',36]];
function rel(p){return path.relative(ROOT,p).replaceAll(path.sep,'/')}
async function exists(p){try{await fs.access(p);return true}catch{return false}}
async function dirs(p){if(!(await exists(p)))return[];return(await fs.readdir(p,{withFileTypes:true})).filter(e=>e.isDirectory()).map(e=>e.name)}
async function files(p){if(!(await exists(p)))return[];return(await fs.readdir(p,{withFileTypes:true})).filter(e=>e.isFile()).map(e=>e.name)}
function err(m){errors.push(m)}function warn(m){warnings.push(m)}
async function validateFiles(dir){for(const name of await files(dir)){const full=path.join(dir,name),ext=path.extname(name).toLowerCase(),stem=path.basename(name,ext);if(!SOURCE_EXT.has(ext))err(`Unsupported source format: ${rel(full)}`);if(!/^\d{2}$/.test(stem))err(`Source filename must be two-digit positional name: ${rel(full)}`);if(RASTER_EXT.has(ext)){const stat=await fs.stat(full);if(stat.size>WARN_RASTER_BYTES){const msg=`Oversized raster (${(stat.size/1024/1024).toFixed(2)} MiB): ${rel(full)}`;strictAssets?err(msg):warn(msg)}}}}
async function validateMaterialTree(){if(!(await exists(MATERIAL_ROOT))){err('materyaller/ is missing');return}for(const course of await dirs(MATERIAL_ROOT)){if(!COURSE_DIRS.has(course)){err(`Unknown course material root: materyaller/${course}`);continue}const cdir=path.join(MATERIAL_ROOT,course);for(const week of await dirs(cdir)){if(!/^hafta\d{2}$/.test(week)){err(`Week directory must be haftaNN: ${rel(path.join(cdir,week))}`);continue}const wdir=path.join(cdir,week);for(const top of await dirs(wdir)){if(top==='thumbs'){err(`Source thumbs/ is forbidden: ${rel(path.join(wdir,top))}`);continue}if(!TOP_LEVEL.has(top)){err(`Unknown material type: ${rel(path.join(wdir,top))}`);continue}const tdir=path.join(wdir,top);if(top==='olcme-degerlendirme'){for(const child of await dirs(tdir)){if(!ASSESSMENT.has(child))err(`Unknown assessment type: ${rel(path.join(tdir,child))}`);else await validateFiles(path.join(tdir,child))}if((await files(tdir)).length)err(`Files must be inside an assessment subtype: ${rel(tdir)}`)}else if(top==='ogretmen'){for(const child of await dirs(tdir)){if(!TEACHER.has(child))err(`Unknown teacher material type: ${rel(path.join(tdir,child))}`);else await validateFiles(path.join(tdir,child))}if((await files(tdir)).length)err(`Files must be inside a teacher subtype: ${rel(tdir)}`)}else{if((await dirs(tdir)).length)err(`Unexpected nested directory: ${rel(tdir)}`);await validateFiles(tdir)}}}}if(await exists(path.join(ROOT,'5-sinif')))err('Duplicate legacy material root 5-sinif/ must not exist')}
async function validatePlans(){for(const[folder,count]of PLAN_RULES){const dir=path.join(ROOT,folder);if(!(await exists(dir))){err(`Missing daily-plan directory: ${folder}`);continue}const nums=new Map();for(const name of await files(dir)){if(name==='.gitkeep')continue;if(!name.endsWith('.docx')){warn(`Unexpected daily-plan file: ${folder}/${name}`);continue}const m=name.match(/^hafta(\d{2})-/);if(!m){err(`Daily-plan filename must use zero-padded week: ${folder}/${name}`);continue}const n=Number(m[1]);if(nums.has(n))err(`Duplicate daily plan for week ${n}: ${folder}`);nums.set(n,name)}for(let n=1;n<=count;n++)if(!nums.has(n))err(`Missing daily plan: ${folder} week ${n}`);for(const n of nums.keys())if(n<1||n>count)err(`Out-of-range daily plan: ${folder} week ${n}`)}}
async function redirectRoutes(){const out=new Set(['/']);const p=path.join(ROOT,'_redirects');if(!(await exists(p)))return out;const text=await fs.readFile(p,'utf8');for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const from=line.split(/\s+/)[0];if(from)out.add(from)}return out}
function isExternalRef(ref){return/^(?:https?:|mailto:|tel:|data:|javascript:|\/\/)/i.test(ref)}
async function validateStaticHtmlLinks(){const routes=await redirectRoutes(),htmlFiles=(await files(ROOT)).filter(x=>x.endsWith('.html')).sort();for(const file of htmlFiles){if(LEGACY_HTML_LINK_EXCLUDES.has(file))continue;const text=await fs.readFile(path.join(ROOT,file),'utf8'),re=/(?:href|src)\s*=\s*["']([^"']+)["']/gi;let m;while((m=re.exec(text))){const original=m[1].trim();if(!original||original==='#'||original.startsWith('#')||isExternalRef(original))continue;const clean=original.split('#')[0].split('?')[0];if(!clean||clean==='/')continue;if(clean.startsWith('/')&&routes.has(clean))continue;const target=clean.startsWith('/')?path.join(ROOT,clean.slice(1)):path.resolve(path.dirname(path.join(ROOT,file)),clean);let valid=await exists(target);if(!valid&&clean.startsWith('/')&&!path.extname(clean))valid=await exists(`${target}.html`);if(!valid)err(`Broken local HTML reference: ${file} -> ${original}`)}}}
function planCountFromPath(p){if(p.includes('gunluk-planlar-5sinif')||p.includes('gunluk-planlar-6sinif'))return 37;if(p.includes('gunluk-planlar-robotik')||p.includes('gunluk-planlar-yapay-zeka'))return 36;return null}
async function validateClassroomPlanLinks(){const runtime=await fs.readFile(path.join(ROOT,'classroom-v2.js'),'utf8');if(!/C\.plan\.replace\(\s*['"]\{n\}['"]\s*,\s*pad\(/.test(runtime))err('classroom-v2.js: expected zero-padded C.plan expansion via pad()');for(const[file,count]of CLASSROOM_PLAN_RULES){const text=await fs.readFile(path.join(ROOT,file),'utf8'),m=text.match(/window\.KESKINLAB_COURSE\s*=\s*(\{[\s\S]*?\});/);if(!m){err(`${file}: KESKINLAB_COURSE config not found`);continue}let config;try{config=JSON.parse(m[1])}catch(e){err(`${file}: KESKINLAB_COURSE is not valid JSON (${e.message})`);continue}if(!config.plan||!config.plan.includes('{n}')){err(`${file}: plan template must contain {n}`);continue}for(let n=1;n<=count;n++){const target=config.plan.replace('{n}',String(n).padStart(2,'0'));if(!(await exists(path.join(ROOT,target))))err(`Broken Classroom daily-plan link: ${file} week ${n} -> ${target}`)}}}
async function validateHomePlanLinks(){const text=await fs.readFile(path.join(ROOT,'home-v2.js'),'utf8'),templates=[...text.matchAll(/plan\s*:\s*n\s*=>\s*`([^`]+)`/g)].map(m=>m[1]);if(templates.length!==4){err(`home-v2.js: expected 4 daily-plan factories, found ${templates.length}`);return}for(const tpl of templates){let factory;try{factory=new Function('n',`return \`${tpl}\`;`)}catch(e){err(`home-v2.js: cannot evaluate daily-plan factory (${e.message})`);continue}const sample=factory(1),count=planCountFromPath(sample);if(!count){err(`home-v2.js: unknown daily-plan factory target: ${sample}`);continue}for(let n=1;n<=count;n++){const target=factory(n);if(!(await exists(path.join(ROOT,target))))err(`Broken homepage daily-plan link: week ${n} -> ${target}`)}}}
async function validateDynamicPlanLinks(){await validateClassroomPlanLinks();await validateHomePlanLinks()}
async function validateGenerated(){const materialPath=path.join(ROOT,'generated','materials.json'),coursePath=path.join(ROOT,'generated','courses.json');if(!(await exists(materialPath))){err('generated/materials.json not present after generate');return}if(!(await exists(coursePath))){err('generated/courses.json not present after generate');return}let materials,courses;try{materials=JSON.parse(await fs.readFile(materialPath,'utf8'));courses=JSON.parse(await fs.readFile(coursePath,'utf8'))}catch(e){err(`Generated JSON is invalid: ${e.message}`);return}if(materials.schemaVersion!==2)err(`generated/materials.json schemaVersion must be 2; got ${materials.schemaVersion}`);if(courses.schemaVersion!==2)err(`generated/courses.json schemaVersion must be 2; got ${courses.schemaVersion}`);for(const[course,c]of Object.entries(materials.courses||{})){for(const[wk,w]of Object.entries(c.weeks||{})){for(const m of w.materials||[]){for(const d of m.downloads||[])if(!(await exists(path.join(ROOT,d.href))))err(`Generated material download missing: ${course} week ${wk} -> ${d.href}`);if(m.preview&&!(await exists(path.join(ROOT,m.preview))))err(`Generated preview missing: ${m.preview}`);if(m.webPreview&&!(await exists(path.join(ROOT,m.webPreview))))err(`Generated web preview missing: ${m.webPreview}`);if(m.thumbnail&&!(await exists(path.join(ROOT,m.thumbnail))))err(`Generated thumbnail missing: ${m.thumbnail}`)}}}}
async function main(){await validateMaterialTree();await validatePlans();await validateStaticHtmlLinks();await validateDynamicPlanLinks();await validateGenerated();for(const w of warnings)console.warn(`WARN  ${w}`);for(const e of errors)console.error(`ERROR ${e}`);console.log(`KeskinLab validation: ${errors.length} error(s), ${warnings.length} warning(s)`);if(errors.length)process.exit(1)}
main().catch(e=>{console.error(e);process.exit(1)});
