(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0');
const state={lesson:null,index:0,revealed:new Set(),selected:null,placed:new Map()};
const els={stage:$('#stage'),nav:$('#chapterNav'),loading:$('#loading'),prev:$('#prevBtn'),next:$('#nextBtn'),chapterLabel:$('#chapterLabel'),stepLabel:$('#stepLabel'),fill:$('#progressFill'),promptTitle:$('#promptTitle'),promptText:$('#promptText'),promptHint:$('#promptHint'),promptIcon:$('#promptIcon'),promptAction:$('#promptAction'),teacher:$('#teacherDrawer'),teacherContent:$('#teacherContent'),scrim:$('#scrim')};
function current(){return state.lesson.steps[state.index]}
function chapter(step=current()){return state.lesson.chapters.find(c=>c.id===step.chapter)||state.lesson.chapters[0]}
function stepIndex(id){return state.lesson.steps.findIndex(s=>s.id===id)}
function firstOfChapter(id){return state.lesson.steps.findIndex(s=>s.chapter===id)}
function stageBrand(){return `<div class="stage-brand"><img src="../brand/devre-karakteri.svg" alt=""><span>Keskin<span>Lab</span></span></div>`}
function header(step){return `<div class="slide-head"><span class="step-kicker">${esc(step.student?.label||step.tymm?.phaseLabel||'DERS AKIŞI')}</span><span class="step-count">${pad(state.index+1)} / ${pad(state.lesson.steps.length)}</span></div>`}
function renderQuestion(step){const open=state.revealed.has(step.id);const reveal=step.reveal?`<div class="reveal ${open?'open':''}"><b>${esc(step.reveal.title||'')}</b><p>${esc(step.reveal.text||'')}</p></div>`:'';return `<div class="slide">${header(step)}<div class="slide-body"><h1 class="big-title">${esc(step.student?.title||'')}</h1><div class="accent-line"></div>${step.student?.lead?`<p class="lead">${esc(step.student.lead)}</p>`:''}${reveal}</div>${stageBrand()}</div>`}
function renderConcepts(step){return `<div class="slide">${header(step)}<div class="slide-body"><h1 class="big-title">${esc(step.student?.title||'')}</h1><div class="concepts">${(step.concepts||[]).map(c=>`<div class="concept"><b>${esc(c.term)}</b><p>${esc(c.copy)}</p></div>`).join('')}</div></div>${stageBrand()}</div>`}
function renderTask(step){return `<div class="slide">${header(step)}<div class="slide-body"><h1 class="big-title">${esc(step.student?.title||'')}</h1>${step.student?.foot?`<p class="lead">${esc(step.student.foot)}</p>`:''}<div class="task-list">${(step.prompts||[]).map((p,i)=>`<div class="task"><span>${pad(i+1)}</span><b>${esc(p)}</b></div>`).join('')}</div></div>${stageBrand()}</div>`}
function renderCompare(step){const a=step.compare?.left||{},b=step.compare?.right||{};return `<div class="slide">${header(step)}<div class="slide-body"><h1 class="big-title">${esc(step.student?.title||'')}</h1><div class="compare"><div class="compare-card"><small>${esc(a.label||'GEÇMİŞ')}</small><h3>${esc(a.title||'')}</h3><p>${esc(a.copy||'')}</p></div><div class="compare-arrow">→</div><div class="compare-card"><small>${esc(b.label||'GÜNÜMÜZ')}</small><h3>${esc(b.title||'')}</h3><p>${esc(b.copy||'')}</p></div></div>${step.compare?.caption?`<p class="lead">${esc(step.compare.caption)}</p>`:''}</div>${stageBrand()}</div>`}
function renderCheckpoint(step){return `<div class="checkpoint"><div class="slide">${header(step)}<div class="slide-body"><h1 class="big-title">${esc(step.student?.title||'')}</h1><div class="accent-line"></div><p class="lead">${esc(step.student?.lead||'')}</p></div>${stageBrand()}</div></div>`}
function renderActivity(step){const used=new Set([...state.placed.values()].flat());return `<div class="slide">${header(step)}<div class="slide-body"><h1 class="big-title">${esc(step.student?.title||'')}</h1>${step.student?.lead?`<p class="lead">${esc(step.student.lead)}</p>`:''}<div class="activity-grid"><div class="item-pool">${(step.items||[]).map(x=>`<button class="item-btn ${state.selected===x.id?'selected':''} ${used.has(x.id)?'used':''}" data-item="${esc(x.id)}"><b>${esc(x.label)}</b><small>${esc(x.hint||'')}</small></button>`).join('')}</div><div class="zones">${(step.categories||[]).map(z=>`<button class="zone" data-zone="${esc(z.id)}"><b>${esc(z.label.toLocaleUpperCase('tr-TR'))}</b><div class="chips">${(state.placed.get(z.id)||[]).map(id=>{const it=step.items.find(x=>x.id===id);return `<span class="chip">${esc(it?.label||id)}</span>`}).join('')}</div></button>`).join('')}</div></div></div>${stageBrand()}</div>`}
function renderGeneric(step){return `<div class="slide">${header(step)}<div class="slide-body"><h1 class="big-title">${esc(step.student?.title||'')}</h1>${step.student?.lead?`<p class="lead">${esc(step.student.lead)}</p>`:''}</div>${stageBrand()}</div>`}
function renderStage(){const step=current();let html='';if(step.layout==='question'||step.layout==='exit')html=renderQuestion(step);else if(step.layout==='concepts')html=renderConcepts(step);else if(step.layout==='task')html=renderTask(step);else if(step.layout==='compare')html=renderCompare(step);else if(step.layout==='checkpoint')html=renderCheckpoint(step);else if(step.layout==='activity')html=renderActivity(step);else html=renderGeneric(step);els.stage.innerHTML=html;bindActivity(step)}
function bindActivity(step){if(step.layout!=='activity')return;els.stage.querySelectorAll('[data-item]').forEach(b=>b.addEventListener('click',()=>{if(b.classList.contains('used'))return;state.selected=state.selected===b.dataset.item?null:b.dataset.item;render()}));els.stage.querySelectorAll('[data-zone]').forEach(b=>b.addEventListener('click',()=>{if(!state.selected)return;const arr=state.placed.get(b.dataset.zone)||[];arr.push(state.selected);state.placed.set(b.dataset.zone,arr);state.selected=null;render()}))}
function renderNav(){const step=current();els.nav.innerHTML=state.lesson.chapters.map((c,i)=>{const count=state.lesson.steps.filter(s=>s.chapter===c.id).length;return `<button class="chapter-btn ${step.chapter===c.id?'active':''}" data-chapter="${esc(c.id)}" data-n="${pad(i+1)}"><strong>${esc(c.title)}</strong><small>${count} ADIM</small></button>`}).join('');els.nav.querySelectorAll('[data-chapter]').forEach(b=>b.addEventListener('click',()=>go(firstOfChapter(b.dataset.chapter))))}
function renderPrompt(){const s=current(),m=s.layout;const presets={question:['?','DÜŞÜN VE PAYLAŞ','Önce öğrenci sesi; ardından ders devam eder.','SOR · BEKLE · PAYLAŞ'],activity:['↔','TAHTADA BİRLİKTE YAPIN','Bir kart seç, sonra uygun alana dokun.','DOKUN · SEÇ · YERLEŞTİR'],compare:['↔','KARŞILAŞTIR','Benzerlik ve farklılıkları öğrenciler söylesin.','BAK · KARŞILAŞTIR · SÖYLE'],task:['✓','GÖREV','Yönergeyi okuyun ve uygulamaya geçin.','UYGULA · PAYLAŞ'],checkpoint:['●','DEVAM NOKTASI','Dersi burada bırakabilir veya buradan yeniden başlayabilirsiniz.','BÖLÜM BAŞLANGICI'],concepts:['→','KAVRAMLARI KUR','Kavramları örneklerle ilişkilendirerek ilerleyin.','GÖSTER · KONUŞ · DEVAM ET'],exit:['✓','ÇIKIŞ BİLETİ','Öğrenmeyi kısa bir öğrenci cevabıyla görünür kılın.','DÜŞÜN · CEVAPLA']};const p=presets[m]||['→','DERS AKIŞI','Bu ekran anlatım ve gözlem için kullanılır.','DEVAM ET'];els.promptIcon.textContent=p[0];els.promptTitle.textContent=p[1];els.promptText.textContent=s.student?.lead||p[2];els.promptHint.textContent=p[3];const hasReveal=!!s.reveal;els.promptAction.hidden=!hasReveal;if(hasReveal){els.promptAction.textContent=state.revealed.has(s.id)?'CEVABI KAPAT':'CEVABI GÖSTER';els.promptAction.onclick=()=>{state.revealed.has(s.id)?state.revealed.delete(s.id):state.revealed.add(s.id);render()}}}
function renderTeacher(){const s=current(),t=s.teacher||{},refs=s.sourceRefs||[];els.teacherContent.innerHTML=`<div class="teacher-block"><small>ÖĞRETMEN NOTU</small><p>${esc(t.note||'Bu adım için ek not yok.')}</p></div>${t.timeHint?`<div class="teacher-block"><small>SÜRE İPUCU</small><p>${esc(t.timeHint)}</p></div>`:''}<div class="teacher-block"><small>PEDAGOJİK ROL</small><p>${esc(s.tymm?.phaseLabel||s.mode||'')}</p></div>${refs.length?`<div class="teacher-block"><small>KAYNAK BAĞLANTISI</small><p>${refs.map(esc).join(' · ')}</p></div>`:''}`}
function updateProgress(){const s=current(),c=chapter(s);els.chapterLabel.textContent=(c?.title||'DERS').toLocaleUpperCase('tr-TR');els.stepLabel.textContent=`${pad(state.index+1)} / ${pad(state.lesson.steps.length)}`;els.fill.style.width=`${((state.index+1)/state.lesson.steps.length)*100}%`;els.prev.disabled=state.index===0;els.next.textContent=state.index===state.lesson.steps.length-1?'✓':'SONRAKİ →'}
function updateUrl(){const u=new URL(location.href);u.searchParams.set('course','5-sinif');u.searchParams.set('week','01');u.searchParams.set('step',current().id);history.replaceState(null,'',u)}
function render(){renderStage();renderNav();renderPrompt();renderTeacher();updateProgress();updateUrl()}
function go(i){if(!Number.isInteger(i)||i<0||i>=state.lesson.steps.length)return;state.index=i;state.selected=null;state.placed=new Map();render()}
function openDrawer(){els.teacher.classList.add('open');els.teacher.setAttribute('aria-hidden','false');els.scrim.hidden=false}
function closeDrawer(){els.teacher.classList.remove('open');els.teacher.setAttribute('aria-hidden','true');els.scrim.hidden=true}
async function load(){try{const r=await fetch('lessons/5-sinif/hafta-01.json',{cache:'no-store'});if(!r.ok)throw new Error(`Ders verisi yüklenemedi (${r.status})`);state.lesson=await r.json();if(!Array.isArray(state.lesson.steps)||!state.lesson.steps.length)throw new Error('Ders adımları bulunamadı.');const requested=new URL(location.href).searchParams.get('step');const i=requested?stepIndex(requested):-1;state.index=i>=0?i:0;els.loading.classList.add('hidden');render()}catch(e){console.error(e);els.loading.innerHTML=`<div class="loading-mark">!</div><strong>Ders açılamadı</strong><span>${esc(e.message)}</span>`}}
els.prev.addEventListener('click',()=>go(state.index-1));els.next.addEventListener('click',()=>{if(state.index<state.lesson.steps.length-1)go(state.index+1)});$('#teacherBtn').addEventListener('click',openDrawer);$('#notesBtn').addEventListener('click',openDrawer);$('#closeDrawer').addEventListener('click',closeDrawer);els.scrim.addEventListener('click',closeDrawer);$('#fullscreenBtn').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();if(e.target.matches('button,input,textarea,select'))return;if(e.key==='ArrowRight'||e.key==='PageDown')go(state.index+1);if(e.key==='ArrowLeft'||e.key==='PageUp')go(state.index-1)});load();
})();
